version: "3.8"

services:
  face-api:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: face-grab-gpu
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./face_index.faiss:/app/face_index.faiss
      - ./face_metadata.db:/app/face_metadata.db
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
  tensorflow:
    image: tensorflow/tensorflow:2.15.0-gpu
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./models:/models
    networks:
      - app-network
    command: tail -f /dev/null
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
networks:
  app-network:
    driver: bridge