version: "3.8"

services:
  face-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-grab-gpu
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./face_index.faiss:/app/face_index.faiss
      - ./face_metadata.db:/app/face_metadata.db
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
